### ISSUE TITLE
Routing subpages

### ISSUE THREAD

**Issue by kalken** [jmfurlott/react-isomorphic-boilerplate#1]
Thanks for an awsome app!

Although i found a small issue.

I think we need 
<code>app.get('/*', function (req, res) {</code> at line 12 in /src/server/server.js. Otherwise its not possible to access http://localhost:3000/some_subpage directly on the initial server render. With just <code>app.get('/', function (req, res) {</code> nothing else but "/" seem to match, and initial rendering of any subpage fail.

is this the correct approach or am i missing something?

**Comment by jmfurlott** [comment]
@kalken thanks for the kind words.  

You are absolutely right!  This was the beginning of a project that I was working on and made that change later without even thinking about it haha

**Comment by jmfurlott** [comment]
Fixed f42b083e2e0ef33e163ec204621e834f95438ca5
