### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by kalken** [jmfurlott/react-isomorphic-boilerplate#2]
It seems that  React.renderToString can result in invalid checksum warnings on the frontend (e.g the react dom id's don't match on rerender. People suggest using React.renderToStaticMarkup to solve this. Also it seems like having scripts outside the body or head tag is not recommended (in index.jade).

what i ended up with to solve the problem:
<b>src/server/server.js:</b>

```
app.get('/*', function (req, res) {
  Router.run(routes, req.url, Handler => {
    res.render('index',{
      markup: React.renderToStaticMarkup(<Handler/>)
    });
  });
});
```

<b>src/views/index.jade:</b>

```
body
    div#app
      != markup
    script(src='http://localhost:8080/js/app.js', defer)
```

I'm pretty new at this so any input would be appreciated.

**Comment by jmfurlott** [comment]
According to the top level api, renderToStaticMarkup does the same as renderToString but stripes the `data-react-id` attributes.  

Hmm, I am not getting the warning that you are getting though! With the invalid checksum.  I'll leave this open to see if other people get it though

Thanks @kalken

**Comment by kalken** [comment]
I did not have these warnings until i made a more complex site (with a lot of divs and navbars and menues). I'm using material-ui to render most components.

with renderToString the message is this:
<b>
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) :Roboto, sans-serif;false:rgba(0,0,0,0);
 (server) :Roboto, sans-serif;-webkit-tap-highligh
</b>
Error goes away by changing to renderToStaticMarkup.

**Comment by TheRusskiy** [comment]
Thank you, @kalken, changing it to `renderToStaticMarkup` did solve the problem!
