### ISSUE TITLE
JSX ?

### ISSUE THREAD

**Issue by daslicht** [jmfurlott/react-isomorphic-boilerplate#8]
Hi,
when I edit the code in VS Code I get the following errors (and more in other files):

https://github.com/Microsoft/vscode/issues/408

If I change the filetypes to jsx the errors are gone?

I tried converting the project to use jsx but I do not have success yet :/

**Comment by jmfurlott** [comment]
I am not sure what the errors are for visual studio but you have to change
the webpack to use jsx files and js files. I am pretty sure it's only
checking for js files but I am afk right now so I can't be certain

On Saturday, November 21, 2015, Marc Wensauer notifications@github.com
wrote:

> Hi,
> when I edit the code in VS Code I get the following errors (and more in
> other files):
> 
> Microsoft/vscode#408 https://github.com/Microsoft/vscode/issues/408
> 
> If I change the filetypes to jsx the errors are gone?
> 
> I tried converting the project to use jsx but I do not have success yet :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmfurlott/react-isomorphic-boilerplate/issues/8.

## 

Joseph Furlott

727-560-6201
jmfurlott.com
@jmfurlott http://twitter.com/jmfurlott

**Comment by daslicht** [comment]
The error seams to be a bug in VS Studio, In Atom anything is fine. Thanks !
